package gov.nist.csd.pm.common.exceptions;

public class ErrorCodes {
    public static final int ERR_ASSIGNMENT_DOES_NOT_EXIST        = 6001;
    public static final int ERR_PROHIBITION_NAME_EXISTS          = 6002;
    public static final int ERR_PROHIBITION_RESOURCE_EXISTS      = 6003;
    public static final int ERR_NO_ID                            = 6004;
    public static final int ERR_ASSIGNMENT_EXISTS                = 6005;
    public static final int ERR_INVALID_PROPERTY                 = 6006;
    public static final int ERR_INVALID_PROHIBITION_SUBJECT_TYPE = 6007;
    public static final int ERR_NODE_NOT_FOUND                   = 6008;
    public static final int ERR_NO_USER_PARAMETER                = 6009;
    public static final int ERR_ASSOCIATION_DOES_NOT_EXIST       = 6010;
    public static final int ERR_NULL_NAME                        = 6011;
    public static final int ERR_PROHIBITION_RESOURCE_DOES_NOT_EXIST = 6012;
    public static final int ERR_NO_SUBJECT_PARAMETER                = 6013;
    public static final int ERR_CONFIGURATION                       = 6014;
    public static final int ERR_PROPERTY_NOT_FOUND                  = 6015;
    public static final int ERR_NAME_IN_NAMESPACE_NOT_FOUND         = 6016;
    public static final int ERR_NODE_NAME_EXISTS                    = 6017;
    public static final int ERR_INVALID_NODETYPE                    = 6018;
    public static final int ERR_PROHIBITION_SUBJECT_DOES_NOT_EXIST  = 6019;
    public static final int ERR_NULL_TYPE                           = 6020;
    public static final int ERR_NODE_NAME_EXISTS_IN_NAMESPACE       = 6021;
    public static final int ERR_PROHIBITION_DOES_NOT_EXIST          = 6022;
    public static final int ERR_SESSION_DOES_NOT_EXIST              = 6023;
    public static final int ERR_ACCESS_DENIED                       = 6024;
    public static final int ERR_NODE_ID_EXISTS                      = 6025;
    public static final int ERR_ASSOCIATION_EXISTS                  = 6026;
    public static final int ERR_MISSING_PERMISSIONS                 = 6027;
    public static final int ERR_SESSION_USER_NOT_FOUND              = 6028;
    public static final int ERR_UNEXPECTED_NUMBER_OF_NODES          = 6029;
    public static final int ERR_INVALID_ASSIGNMENT                  = 6030;
    public static final int ERR_NO_BASE_ID                          = 6031;
    public static final int ERR_NO_PROCESS                          = 6032;
    public static final int ERR_MALFORMED_PDL                       = 6033;
    public static final int ERR_INVALID_ASSOCIATION                 = 6034;
    public static final int ERR_NODE_EXISTS              = 6035;
    public static final int ERR_POLICY_NAME_EXISTS       = 6036;
    public static final int ERR_INVALID_CREDENTIALS      = 6037;
    public static final int ERR_LOADER                   = 6038;
    public static final int ERR_NULL_NODE_CTX            = 6039;
    public static final int ERR_MEM_GRAPH_NODE_RETRIEVAL = 6040;
    public static final int ERR_NOT_IMPLEMENTED          = 6041;
    public static final int ERR_LOADING_DB_CONFIG_PROPS  = 6042;
    public static final int ERR_HASHING_USER_PSWD  = 6043;
    public static final int ERR_NULL_OPERATIONS  = 6044;
    public static final int ERR_AUTH  = 6045;

    public static final int ERR_DB  = 7000;
}
